//
// Generated by CocoaPods-Keys
// on 11/03/2015
// For more information see https://github.com/orta/cocoapods-keys
//

#import <objc/runtime.h>
#import <Foundation/NSDictionary.h>
#import "FakeKeys.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation FakeKeys

#pragma clang diagnostic pop

+ (BOOL)resolveInstanceMethod:(SEL)name
{
  NSString *key = NSStringFromSelector(name);
  NSString * (*implementation)(FakeKeys *, SEL) = NULL;

  if (!implementation) {
    return [super resolveInstanceMethod:name];
  }

  return class_addMethod([self class], name, (IMP)implementation, "@@:");
}


static char FakeKeysData[] = "";

- (NSString *)description
{
  return [@{
  } description];
}

- (id)debugQuickLookObject
{
  return [self description];
}

@end
